// <auto-generated />
namespace ImgLab.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class HashUpd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HashUpd));
        
        string IMigrationMetadata.Id
        {
            get { return "201801190634295_HashUpd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
